#!/usr/bin/env bash
set -e

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EXPECTED_DIR="$HOME/.dotfiles"
[ "$BASEDIR" != "$EXPECTED_DIR" ] && {
  echo "Error: dotfiles folder should be at '$EXPECTED_DIR'. Exiting."
  exit 1
}

[[ $OSTYPE == *darwin* ]] && CONFIG="osx.conf.yaml"
[[ $OSTYPE == *linux* ]] && CONFIG="linux.conf.yaml"
[ -z "$CONFIG" ] && {
  echo "Error: $OSTYPE not recognized. Exiting."
  exit 1
}
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
